import { Lato, Poppins, Oswald} from "next/font/google";
import "./globals.css";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
   weight: ["400", "700"],
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
   weight: ["400", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
   weight: ["400", "700"],
});

export const metadata = {
  title: "Shop-Co | All Your Needs Are Here",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${poppins.variable} ${oswald.variable} antialiased`}
      >
        {children}
        
      </body>
      
    </html>
  );
}
